version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "28017:27017"
    environment:
      - MONGO_INITDB_DATABASE=example-spring-person
    volumes:
      - mongo-data:/data/mongodb
    networks:
      - mongo-net
  mongo-express:
    image: mongo-express
    ports:
      - "18081:8081"
    networks:
      - mongo-net
    depends_on:
      - mongo
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.1.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_CREATE_TOPICS: "person-created:1:1,person-name-updated:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - 'kafka-data:/var/run/docker.sock'
volumes:
  mongo-data:
  kafka-data:
networks:
  mongo-net:
    driver: bridge
